### ISSUE TITLE
Add examples for plotting capabilities.

### ISSUE THREAD

**Issue by KelSolaar** [njsmith/pycam02ucs#7]
I'm loosely following the repo, and wanted to take a look a the plotting aspect of things. After really quick code inspection I didn't find an easy entry point to launch anything related to plotting. Do you have an example?

**Comment by njsmith** [comment]
Hi Thomas,

Not sure what you mean by "plotting aspect of things". The repository isn't
really set up very well for public consumption at the moment -- it contains
on the one hand utility libraries for doing certain color calculations
(esp. a CIECAM02 implementation), and then there's also some
code-in-progress that we've been experimenting with for using CIECAM02 to
visualize/design colormaps. Of course you're welcome to play around, just
mind the dust :-)

There is a little post here describing how to run the colormap visualizer
in case that's what you're interested in:

http://thread.gmane.org/
<http://thread.gmane.org/gmane.comp.python.matplotlib.devel/13122/focus=13214>
gmane.comp.python.matplotlib.devel
<http://thread.gmane.org/gmane.comp.python.matplotlib.devel/13122/focus=13214>
/13122/focus=13214
<http://thread.gmane.org/gmane.comp.python.matplotlib.devel/13122/focus=13214>

I'm loosely following the repo, and wanted to take a look a the plotting
aspect of things. After really quick code inspection I didn't find an easy
entry point to launch anything related to plotting. Do you have an example?

—
Reply to this email directly or view it on GitHub
<https://github.com/njsmith/pycam02ucs/issues/7>.

**Comment by KelSolaar** [comment]
Thank you! Perfect, I was curious to see what it was doing and with the context it makes sense.

Cheers,

Thomas
